version: '3.8'

networks:
  petclinic_network:
    driver: bridge

services:
  petclinic:
    image: petclinic-pipeline-script
    ports:
      - "9090:8080"
    environment:
      - JAVA_OPTS=-Dspring.profiles.active=mysql\
        -Dspring.datasource.url=jdbc:mysql://mysql/petclinic
    networks:
      - petclinic_network
    depends_on:
      - mysql
  mysql:
    hostname: mysql
    networks:
      - petclinic_network
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"