version: '3.8'
services:
  petclinic:
    image: petclinic-pipeline
    ports:
      - "9090:8080"
    environment:
      - JAVA_OPTS=-Dspring.profiles.active=mysql\
        -Dspring.datasource.url=jdbc:mysql://mysql/petclinic
